### ISSUE TITLE
A plugin for drone ci

### ISSUE THREAD

**Issue by lunny** [covergates/covergates#10]
If there is a plugin for drone ci to commit report it's better because we use drone ci. A plugin of drone is in fact a docker image.

**Comment by luwol03** [comment]
Hello,

here is my version of a drone plugin for covergates. you can just take it over if you want.
I like drone a lot and can't wait any longer :joy: that's why i wrote a plugin.

`entrypoint.sh`
```bash
#!/bin/sh -l
export API_URL=${PLUGIN_API_URL}

echo "commit: $DRONE_COMMIT_SHA"

echo "/bin/covergates upload --report ${PLUGIN_REPORT_ID} --type ${PLUGIN_REPORT_TYPE} ${PLUGIN_REPORT_FILE}"
/bin/covergates upload --report ${PLUGIN_REPORT_ID} --type ${PLUGIN_REPORT_TYPE} ${PLUGIN_REPORT_FILE}

if [[ -n ${PLUGIN_PULL_REQUEST} ]] && [[ $DRONE_BUILD_EVENT == "pull_request" ]]; then
  /bin/covergates comment --report ${PLUGIN_REPORT_ID} --number ${DRONE_PULL_REQUEST}
fi
```

Dockerstuff is the same as [this](https://github.com/covergates/github-actions).

and you can use it in your pipeline like this:
```yml
steps:
  - name: install
    image: node:14
    commands:
      - npm i

  - name: test
    image: node:14
    commands:
      - npm test

  - name: covergates
    image: covergates-drone
    settings:
      api_url: <API_URL>
      report_id: <REPORT_ID>
      report_type: <REPORT_TYPE>
      report_file: <REPORT_FILE>
      pull_request: <bool>
```
