### ISSUE TITLE
Production setup and configuration for Docker Swarm, Traefik and Gitea

### ISSUE THREAD

**Issue by prologic** [covergates/covergates#32]
Hey folks 👋

Just wanted to share my config that I finally got working:

- Runs on Docker Swarm
- Uses Treefik for ingress
- Uses Gitea for OAuth

1. Fist build the Docker image:

```console
docker build -t covergates .
```

2. Setup an Application in Gitea, see attached:

<img width="1392" alt="Screen Shot 2022-09-29 at 11 06 46" src="https://user-images.githubusercontent.com/1290234/192916815-9375e041-9034-494c-be80-a2e937a1bb4e.png">

Using the following Docker Stack `covergates.yaml`:

```yaml
---
version: "3.8"

services:
  covergates:
    image: covergates
    environment:
      - GATES_DB_NAME=/data/covergates.db
      - GATES_SERVER_PORT=8000
      - GATES_SERVER_ADDR=https://covergates.${DOMAIN:?DOMAIN not configured}
      - GATES_GITEA_SERVER=https://git.${DOMAIN:?DOMAIN not configured}
      - GATES_GITEA_CLIENT_ID=<redacted>
      - GATES_GITEA_CLIENT_SECRET=<redacted>
    volumes:
      - covergates:/data
    networks:
      - traefik
    deploy:
      replicas: 1
      labels:
        - "traefik.enable=true"
        - "traefik.docker.network=traefik"
        - "traefik.http.services.covergates.loadbalancer.server.port=8000"
        - "traefik.http.routers.covergates.rule=Host(`covergates.${DOMAIN:?DOMAIN not configured}`)"
        - "traefik.http.routers.covergates.priority=2"
      resources:
        reservations:
          cpus: "0.25"
          memory: 128M
        limits:
          cpus: "0.5"
          memory: 256M
      restart_policy:
        condition: any

networks:
  traefik:
    external: true

volumes:
  covergates:
    driver: local
```

3. Deploy with:

```console
export DOMAIN=yourdomain.com
docker stack deploy covergates.yaml
```
